### ISSUE TITLE
Cluster not Reachable when exec Authentication is used

### ISSUE THREAD

**Issue by hofq** [podman-desktop/extension-kubernetes-contexts#398]
### Bug description

For Authentication on Prod we use azure/kubelogin. It seems like it is not compatible to Podman Desktop

### Operating system

macos sonoma 14

### Installation Method

Brew (macOS)

### Version

1.8.0

### Steps to reproduce

- Open Podman Desktop
- Select Azure Cluster, authenticated with kubelogin from azure or with aws-iam-authenticator
- Receive Error below

### Additional context

<img width="584" alt="grafik" src="https://github.com/podman-desktop/extension-kubernetes-contexts/assets/54744977/d4c01b60-7880-4107-b91e-9695245fc69e">

User Authentication snippet Kubelogin:
```yaml
user:
- name: azure-user-roc-kubelogin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--environment"
      - AzurePublicCloud
      - "--server-id"
      - <client id>
      - "--client-id"
      - <client id>
      - "--tenant-id"
      - <tenant id>
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
Used Package for auth:
https://github.com/Azure/kubelogin
<br />

User Authentication snippet Kubelogin:
```yaml
- name: clusterUser_rg-ffdfd-dfdf-dfdf
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--login"
      - azurecli
      - "--server-id"
      - XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      command: kubelogin
      env: null
      installHint: |
        kubelogin is not installed which is required to connect to AAD enabled cluster.

```
